# Load modules

In [101]:
import numpy as np
import pandas as pd

# Get List of Relevant Schools

In [ ]:
bradford_df = pd.read_csv("data/bradford_schools_with_data.csv")
urns = bradford_df["URN"].unique()
bradford_df

,Name,URN,Postcode,Lat,Lon,Website,Attainment 8,Progress 8,Pupil Count
0,Hazelbeck Special School,139977,BD16 1EE,53.841401,-1.827540,https://www.hazelbeck.org/,NaN,NaN,11.0
1,Dixons Trinity Academy,138251,BD5 0BE,53.786414,-1.761281,https://www.dixonsta.com/,54.7,0.72,116.0
2,Otley Prince Henry's Grammar School Specialist...,137704,LS21 2BB,53.912570,-1.694590,https://www.princehenrys.co.uk/,53.4,0.34,278.0
3,Carlton Bolling,147100,BD3 0DU,53.802248,-1.738203,https://www.carltonbolling.co.uk/,43.0,0.27,323.0
4,Bradford Academy,135367,BD4 7QJ,53.776937,-1.732226,https://www.bradfordacademy.co.uk/,33.1,-0.94,230.0
...,...,...,...,...,...,...,...,...,...
68,Trinity Academy Halifax,136094,HX2 9TZ,53.753928,-1.877149,https://halifax.trinitymat.org,43.5,0.00,318.0
69,Green Meadows Academy,148654,LS20 8LS,53.874327,-1.721607,https://greenmeadows.org.uk/,7.3,-1.37,23.0
70,Fairfield School,107802,WF17 8AS,53.720996,-1.665745,https://www.fairfieldschool.uk/,NaN,NaN,10.0
71,Bronte Girls' Secondary Academy,147067,BD4 7EB,53.785564,-1.745519,https://bga.iexel.org.uk/,51.2,0.21,127.0
72,Dixons McMillan Academy,141002,BD5 0JD,53.786417,-1.765239,https://www.dixonsma.com/,47.8,-0.16,114.0

# Load Ofsted Data

## Latest inspections as of 30 June 2026
https://www.gov.uk/csv-preview/6a54efeba6586e258d371d9c/Management_information_-_state-funded_schools_-_latest_inspections_as_at_30_June_2026.csv

In [103]:
inspection_aug_24 = pd.read_csv("data/Management_information_-_state-funded_schools_-_latest_inspections_as_at_31_Aug_2024.csv")
inspection_aug_24.columns

C:\Users\halko\AppData\Local\Temp\ipykernel_14136\3168196119.py:1: DtypeWarning: Columns (0: Multi-academy trust name) have mixed types. Specify dtype option on import or set low_memory=False.
  inspection_aug_24 = pd.read_csv("data/Management_information_-_state-funded_schools_-_latest_inspections_as_at_31_Aug_2024.csv")

Index(['Web link', 'URN', 'LAESTAB', 'School name', 'Ofsted phase',
       'Type of education', 'School open date', 'Admissions policy',
       'Sixth form', 'Designated religious character', 'Religious ethos',
       'Faith grouping', 'Ofsted region', 'Region', 'Local authority',
       'Parliamentary constituency', 'Multi-academy trust UID',
       'Multi-academy trust name', 'Academy sponsor UID',
       'Academy sponsor name', 'Postcode',
       'The income deprivation affecting children index (IDACI) quintile',
       'Total number of pupils', 'Statutory lowest age',
       'Statutory highest age',
       'Latest ungraded inspection number since last graded inspection',
       'Does the ungraded inspection relate to the URN of the current school?',
       'URN at time of the ungraded inspection',
       'LAESTAB at time of the ungraded inspection',
       'School name at time of the ungraded inspection',
       'School type at time of the ungraded inspection',
       'Number of ungraded inspections since the last graded inspection',
       'Date of latest ungraded inspection',
       'Ungraded inspection publication date',
       'Did the latest ungraded inspection convert to a graded inspection?',
       'Ungraded inspection overall outcome',
       'Number of monitoring and urgent inspections since last graded inspection',
       'Inspection number of latest graded inspection', 'Inspection type',
       'Inspection type grouping', 'Event type grouping',
       'Inspection start date', 'Publication date',
       'Does the latest graded inspection relate to the URN of the current school?',
       'URN at time of latest graded inspection',
       'LAESTAB at time of latest graded inspection',
       'School name at time of latest graded inspection',
       'School type at time of latest graded inspection',
       'Overall effectiveness', 'Category of concern', 'Quality of education',
       'Behaviour and attitudes', 'Personal development',
       'Effectiveness of leadership and management',
       'Safeguarding is effective?',
       'Early years provision (where applicable)',
       'Sixth form provision (where applicable)',
       'Previous graded inspection number', 'Previous inspection start date',
       'Previous publication date',
       'Does the previous graded inspection relate to the URN of the current school?',
       'URN at time of previous graded inspection',
       'LAESTAB at time of previous graded inspection',
       'School name at time of previous graded inspection',
       'School type at time of previous graded inspection',
       'Previous graded inspection overall effectiveness',
       'Previous category of concern', 'Previous quality of education',
       'Previous behaviour and attitudes', 'Previous personal development',
       'Previous effectiveness of leadership and management',
       'Previous safeguarding is effective?',
       'Previous early years provision (where applicable)',
       'Previous sixth form provision (where applicable)'],
      dtype='str')

In [104]:
# 147100 Carton Boiling: overall outstanding
# 108114 Woodhouse Grove School: independent
# 142590 Immanuel College: overall good
# 150387 The Calder Learning Trust: new academy, previously overall good
# 107455 Bradford Grammar School: independent
# 149162 Whitcliffe Mount, A Share Academy: overall good
# 134427 TLG Bradford: Closed
# 108083 Benton Park School: new academy (previously Requires Improvement)
# 150001 Parkside School: new acaademy (previously Inadequate) 
# 107585 Hipperholme Grammar School: independent
# 146204 The Whitley AP Academy: overall good
# 134587 The Fountain School: independent

In [105]:
bradford_df = bradford_df.loc[bradford_df["URN"].isin(inspection_aug_24["URN"])]

inspection_aug_24 = inspection_aug_24.drop(columns=[
    "Web link",
    "LAESTAB",
    'Ofsted region', 'Region',
    'Latest ungraded inspection number since last graded inspection',
       'Does the ungraded inspection relate to the URN of the current school?',
       'URN at time of the ungraded inspection',
       'LAESTAB at time of the ungraded inspection',
       'School name at time of the ungraded inspection',
       'School type at time of the ungraded inspection',
       'Number of ungraded inspections since the last graded inspection',
       'Date of latest ungraded inspection',
       'Ungraded inspection publication date',
       'Did the latest ungraded inspection convert to a graded inspection?',
       'Ungraded inspection overall outcome',
        'Does the latest graded inspection relate to the URN of the current school?',
       'URN at time of latest graded inspection',
       'LAESTAB at time of latest graded inspection',
       'School name at time of latest graded inspection',
       'School type at time of latest graded inspection',
        'Previous graded inspection number', 'Previous inspection start date',
       'Previous publication date',
       'Does the previous graded inspection relate to the URN of the current school?',
       'URN at time of previous graded inspection',
       'LAESTAB at time of previous graded inspection',
       'School name at time of previous graded inspection',
       'School type at time of previous graded inspection',
       'Previous graded inspection overall effectiveness',
       'Previous category of concern', 'Previous quality of education',
       'Previous behaviour and attitudes', 'Previous personal development',
       'Previous effectiveness of leadership and management',
       'Previous safeguarding is effective?',
       'Previous early years provision (where applicable)',
       'Previous sixth form provision (where applicable)'
    ])

In [ ]:
inspection_aug_24.merge(
    bradford_df.drop(columns=["Postcode", "Pupil Count"]),
    on="URN",
    validate="1:1"
).to_csv("data/ofsted_bradford_data.csv", index=False)

In [ ]:
missing_urns = set(urns) - set(inspection_aug_24.loc[inspection_aug_24["URN"].isin(urns), "URN"])
bradford_df.loc[bradford_df.URN.isin(missing_urns)]

# 108114 Woodhouse Grove School: independent
# 107460 Jaamiatul Imaam Muhammad Zakaria - religious independent girls school 
# 150387 The Calder Learning Trust: new academy, previously overall good
# 107455 Bradford Grammar School: independent
# 107585 Hipperholme Grammar School: independent
# 107461 Bradford Christian School:  fee paying independent school
# 134587 The Fountain School - fee paying independent muslim school	
# 134429 Al Mumin Primary and Secondary School - independent fee paying Muslim faith school
# 136189 Eternal Light Secondary School - independent fee paying Muslim faith school
# 131960 Broadwood School - small fee paying SEND specialist school
# 134140 Darul Uloom Dawatul Imaan	- independent boarding Muslim boys school
# 137785 Prism Independent School - Hippy dippy bullshit school

,Name,URN,Postcode,Lat,Lon,Website,Attainment 8,Progress 8,Pupil Count
7,Woodhouse Grove School,108114,BD10 0NR,53.839115,-1.698692,https://www.woodhousegrove.co.uk/,17.8,NaN,116.0
12,Jaamiatul Imaam Muhammad Zakaria,107460,BD14 6JX,53.775754,-1.812779,NaN,43.5,NaN,62.0
22,The Calder Learning Trust,150387,HX7 5QN,53.732374,-1.975560,https://www.calderlearningtrust.com,NaN,NaN,NaN
23,Bradford Grammar School,107455,BD9 4JP,53.815200,-1.769148,https://www.bradfordgrammar.com/,27.5,NaN,134.0
50,Hipperholme Grammar School,107585,HX3 8JE,53.728835,-1.813044,https://www.hgsf.org.uk/,48.9,NaN,28.0
52,Bradford Christian School,107461,BD2 1BT,53.820189,-1.760392,https://bradfordchristianschool.com/,50.3,NaN,18.0
58,The Fountain School,134587,BD5 8BP,53.775855,-1.753748,NaN,59.4,NaN,8.0
59,Al Mumin Primary and Secondary School,134429,BD8 7DA,53.806077,-1.761032,https://www.almumin.bradford.sch.uk/,44.2,NaN,10.0
60,Eternal Light Secondary School,136189,BD5 9DH,53.776132,-1.770919,https://eternallightschool.co.uk/,50.3,NaN,27.0
61,Broadwood School,131960,HX2 0RU,53.733292,-1.903443,http://www.keyschildcare.co.uk/services/educat...,3.5,NaN,10.0
62,Darul Uloom Dawatul Imaan,134140,BD4 9PH,53.775241,-1.724721,https://www.dawatulimaan.org/,57.5,NaN,21.0
66,Prism Independent School,137785,BD8 9ES,53.800157,-1.781504,https://www.prismindependentschool.org/,NaN,NaN,14.0

## Load from url

In [9]:
ofsted_df = pd.read_csv("https://explore-education-statistics.service.gov.uk/data-catalogue/data-set/45f7c7a6-4ab2-4527-ab42-bc4b9b1dc0b8/csv")
ofsted_df.columns

Index(['time_period', 'time_identifier', 'geographic_level', 'country_code',
       'country_name', 'region_code', 'region_name', 'old_la_code',
       'new_la_code', 'la_name', 'school_laestab', 'school_urn', 'school_name',
       'school_type', 'education_phase', 'school_phase', 'exclusion',
       'primary_existing_places', 'primary_new_places',
       'secondary_existing_places', 'secondary_new_places',
       'ofsted_quality_of_education', 'ofsted_behaviour_and_attitudes',
       'ofsted_personal_development', 'ofsted_leadership_and_management',
       'ofsted_inspection_date', 'progress_8_rating',
       'primary_progress_in_reading', 'primary_progress_in_maths'],
      dtype='str')

In [ ]:
ofsted_df = pd.read_csv("https://explore-education-statistics.service.gov.uk/data-catalogue/data-set/45f7c7a6-4ab2-4527-ab42-bc4b9b1dc0b8/csv")



bradford_ofsted_df = ofsted_df.loc[ofsted_df["school_urn"].isin(urns)].drop(columns=['geographic_level', 'country_code', 'country_name', 'region_code', 'region_name', 'old_la_code', 'new_la_code', 'la_name', 'school_laestab', "primary_existing_places", "primary_new_places", "primary_progress_in_reading", "primary_progress_in_maths"])

In [12]:
ind_ofsted_df = pd.read_csv("data/Management_information_-_non-association_independent_schools_-_as_at_30_April.csv")

ind_ofsted_df.loc[ind_ofsted_df["URN"].isin(urns)]

,URN,LAESTAB,School name,Type of education,School type,School open date,Sixth Form,Religious character,Religious ethos,Faith grouping,...,Most recent standard inspection: Part 6 overall,Most recent standard inspection: Part 7 overall,Most recent standard inspection: Part 8 overall,Most recent progress monitoring: inspection number,Most recent progress monitoring: inspection type,Most recent progress monitoring: start date,Most recent progress monitoring: academic year,Most recent progress monitoring: publication date,Most recent progress monitoring: overall outcome,Unnamed: 60
267,134587,3806116,The Fountain School,Other Independent School,Independent faith school,29/08/2003,Does not have a sixth form,NaN,Muslim,Muslim,...,Met,Met,Met,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,137785,3806001,Prism Independent School,Other Independent Special School,Independent special school,07/12/2011,Not applicable,NaN,NaN,Non-faith,...,Met,Met,Met,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
set(bradford_df["URN"]) - set(bradford_ofsted_df["school_urn"])

{107455,
 107460,
 107461,
 107585,
 107802,
 108114,
 108117,
 121778,
 131960,
 134140,
 134427,
 134429,
 134587,
 134884,
 135851,
 136189,
 137785,
 139977,
 143533,
 146204,
 146851,
 148654,
 149519}

In [ ]:
((set(bradford_df["Name"]) - set(bradford_ofsted_df["school_name"])) - set(ind_ofsted_df["School name"]))

{'Al Mumin Primary and Secondary School',
 'Bradford Alternative Provision Academy',
 'Bradford Christian School',
 'Bradford Grammar School',
 'Broadwood School',
 "Bronte Girls' Secondary Academy",
 'Brooklands School',
 'Craven Pupil Referral Service',
 'Darul Uloom Dawatul Imaan',
 'Eternal Light Secondary School',
 'Fairfield School',
 'Fulneck School',
 'Green Meadows Academy',
 'Hazelbeck Special School',
 'High Park School',
 'Hipperholme Grammar School',
 'Jaamiatul Imaam Muhammad Zakaria',
 'Oastlers School',
 "St Bede's and St Joseph's Catholic College",
 'TLG Bradford',
 'The Holy Family Catholic School',
 'The Whitley AP Academy',
 'West Specialist Inclusive Learning Centre (Mainsite)',
 'Woodhouse Grove School'}

In [ ]:
new_df = pd.read_csv("https://explore-education-statistics.service.gov.uk/data-catalogue/data-set/e0af2035-828b-4959-8d33-672a9d89ca07/csv")

new_df.columns

Index(['time_period', 'time_identifier', 'geographic_level', 'country_code',
       'country_name', 'region_code', 'region_name', 'old_la_code',
       'new_la_code', 'la_name', 'education_phase', 'rating_type', 'rating',
       'existing_place_count', 'new_place_count'],
      dtype='str')

In [ ]:
# https://reports.ofsted.gov.uk//search?q=139977&location=&lat=&lon=&radius=&level_1_types=0

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

base_domain = "https://reports.ofsted.gov.uk"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}

# We will store each school as a dictionary inside this list
records = []

for urn in urns:
    print(f"\nSearching for URN: {urn}...")
    search_url = f"{base_domain}/search?q={urn}&location=&lat=&lon=&radius=&level_1_types=0"
    
    # 1. Fetch Search Page
    search_response = requests.get(search_url, headers=headers)
    search_soup = BeautifulSoup(search_response.content, 'html.parser')
    
    # 2. Extract First Search Result Link
    h3_tag = search_soup.find("h3", class_="search-result__title")
    first_result = h3_tag.find("a") if h3_tag else None
    
    if not first_result:
        print(f"No results found for URN {urn}.")
        # Append a row with missing data so you know this URN was checked
        records.append({
            "URN": urn,
            "OverallRating": None,
            "Quality of education": None,
            "Behaviour and attitudes": None,
            "Personal development": None,
            "Leadership and management": None
        })
        continue
        
    provider_path = first_result.get("href")
    provider_url = f"{base_domain}{provider_path}"
    print(f"Found provider page: {provider_url}")
    
    # 3. Fetch Provider Page
    provider_response = requests.get(provider_url, headers=headers)
    provider_soup = BeautifulSoup(provider_response.content, 'html.parser')

    # Extract Overall Rating
    overall_rating = None
    result_li_tag = provider_soup.find("li", class_="rating rating--selected heading--sub")
    if result_li_tag and result_li_tag.find("span"):
        overall_rating = result_li_tag.find("span").text.strip()
    
    # Start building the row dictionary for this school
    school_data = {
        "URN": urn,
        "OverallRating": overall_rating
    }

    if overall_rating is None:
        overall_other = provider_soup.find("div", class_="subjudgements__overall")
        if overall_other is not None:
            overall_rating = overall_other.find("strong").text

    # Extract Subjudgements
    rating_blocks = provider_soup.find_all("div", class_="subjudgements__rates__item")
    for block in rating_blocks:
        category_tag = block.find("p")
        rating_tag = block.find("strong")
        
        if category_tag and rating_tag:
            category = category_tag.text.strip().rstrip(':')
            rating = rating_tag.text.strip()
            school_data[category] = rating

    # Append this school's complete record to our list
    records.append(school_data)

# Convert the list of dictionaries directly into a DataFrame
df = pd.DataFrame(records)

# Display the final DataFrame
print("\n--- Final Ofsted Data ---")
print(df)

Searching for URN: 139977...
Found provider page: https://reports.ofsted.gov.uk/provider/25/139977

Searching for URN: 138251...
Found provider page: https://reports.ofsted.gov.uk/provider/23/138251

Searching for URN: 137704...
Found provider page: https://reports.ofsted.gov.uk/provider/23/137704

Searching for URN: 147100...
Found provider page: https://reports.ofsted.gov.uk/provider/23/147100

Searching for URN: 135367...
Found provider page: https://reports.ofsted.gov.uk/provider/28/135367

Searching for URN: 147177...
Found provider page: https://reports.ofsted.gov.uk/provider/23/147177

Searching for URN: 138111...
Found provider page: https://reports.ofsted.gov.uk/provider/23/138111

Searching for URN: 108114...
No results found for URN 108114.

Searching for URN: 108117...
No results found for URN 108117.

Searching for URN: 138304...
Found provider page: https://reports.ofsted.gov.uk/provider/23/138304

Searching for URN: 108079...
Found provider page: https://reports.ofsted.gov.uk/provider/23/108079

Searching for URN: 107395...
Found provider page: https://reports.ofsted.gov.uk/provider/23/107395

Searching for URN: 139975...
Found provider page: https://reports.ofsted.gov.uk/provider/23/139975

Searching for URN: 107460...
Found provider page: https://reports.ofsted.gov.uk/provider/27/107460

Searching for URN: 139351...
Found provider page: https://reports.ofsted.gov.uk/provider/23/139351

Searching for URN: 136736...
Found provider page: https://reports.ofsted.gov.uk/provider/23/136736

Searching for URN: 134884...
Found provider page: https://reports.ofsted.gov.uk/provider/25/134884

Searching for URN: 139182...
Found provider page: https://reports.ofsted.gov.uk/provider/23/139182

Searching for URN: 135935...
Found provider page: https://reports.ofsted.gov.uk/provider/23/135935

Searching for URN: 142590...
Found provider page: https://reports.ofsted.gov.uk/provider/23/142590

Searching for URN: 144946...
Found provider page: https://reports.ofsted.gov.uk/provider/23/144946

Searching for URN: 136905...
Found provider page: https://reports.ofsted.gov.uk/provider/23/136905

Searching for URN: 140326...
Found provider page: https://reports.ofsted.gov.uk/provider/28/140326

Searching for URN: 150387...
Found provider page: https://reports.ofsted.gov.uk/provider/28/150387

Searching for URN: 107455...
No results found for URN 107455.

Searching for URN: 108085...
Found provider page: https://reports.ofsted.gov.uk/provider/23/108085

Searching for URN: 136604...
Found provider page: https://reports.ofsted.gov.uk/provider/23/136604

Searching for URN: 142825...
Found provider page: https://reports.ofsted.gov.uk/provider/23/142825

Searching for URN: 149162...
Found provider page: https://reports.ofsted.gov.uk/provider/23/149162

Searching for URN: 143114...
Found provider page: https://reports.ofsted.gov.uk/provider/23/143114

Searching for URN: 135866...
Found provider page: https://reports.ofsted.gov.uk/provider/28/135866

Searching for URN: 140204...
Found provider page: https://reports.ofsted.gov.uk/provider/23/140204

Searching for URN: 148520...
Found provider page: https://reports.ofsted.gov.uk/provider/23/148520

Searching for URN: 134427...
No results found for URN 134427.

Searching for URN: 146851...
Found provider page: https://reports.ofsted.gov.uk/provider/22/146851

Searching for URN: 142031...
Found provider page: https://reports.ofsted.gov.uk/provider/23/142031

Searching for URN: 138087...
Found provider page: https://reports.ofsted.gov.uk/provider/23/138087

Searching for URN: 143533...
Found provider page: https://reports.ofsted.gov.uk/provider/25/143533

Searching for URN: 136198...
Found provider page: https://reports.ofsted.gov.uk/provider/23/136198

Searching for URN: 136788...
Found provider page: https://reports.ofsted.gov.uk/provider/23/136788

Searching for URN: 108083...
No results found for URN 108083.

Searching for URN: 107439...
Found provider page: https://reports.ofsted.gov.uk/provider/23/107439

Searching for URN: 148545...
Found provider page: https://reports.ofsted.gov.uk/provider/23/148545

Searching for URN: 121778...
Found provider page: https://reports.ofsted.gov.uk/provider/25/121778

Searching for URN: 149299...
Found provider page: https://reports.ofsted.gov.uk/provider/23/149299

Searching for URN: 146198...
Found provider page: https://reports.ofsted.gov.uk/provider/23/146198

Searching for URN: 150001...
Found provider page: https://reports.ofsted.gov.uk/provider/23/150001

Searching for URN: 143112...
Found provider page: https://reports.ofsted.gov.uk/provider/23/143112

Searching for URN: 149011...
Found provider page: https://reports.ofsted.gov.uk/provider/23/149011

Searching for URN: 145173...
Found provider page: https://reports.ofsted.gov.uk/provider/28/145173

Searching for URN: 130909...
Found provider page: https://reports.ofsted.gov.uk/provider/23/130909

Searching for URN: 137036...
Found provider page: https://reports.ofsted.gov.uk/provider/23/137036

Searching for URN: 107585...
No results found for URN 107585.

Searching for URN: 146204...
Found provider page: https://reports.ofsted.gov.uk/provider/22/146204

Searching for URN: 107461...
Found provider page: https://reports.ofsted.gov.uk/provider/27/107461

Searching for URN: 136962...
Found provider page: https://reports.ofsted.gov.uk/provider/23/136962

Searching for URN: 149519...
Found provider page: https://reports.ofsted.gov.uk/provider/25/149519

Searching for URN: 142761...
Found provider page: https://reports.ofsted.gov.uk/provider/23/142761

Searching for URN: 137277...
Found provider page: https://reports.ofsted.gov.uk/provider/23/137277

Searching for URN: 142681...
Found provider page: https://reports.ofsted.gov.uk/provider/23/142681

Searching for URN: 134587...
Found provider page: https://reports.ofsted.gov.uk/provider/27/134587

Searching for URN: 134429...
Found provider page: https://reports.ofsted.gov.uk/provider/27/134429

Searching for URN: 136189...
Found provider page: https://reports.ofsted.gov.uk/provider/27/136189

Searching for URN: 131960...
Found provider page: https://reports.ofsted.gov.uk/provider/27/131960

Searching for URN: 134140...
Found provider page: https://reports.ofsted.gov.uk/provider/27/134140

Searching for URN: 139995...
Found provider page: https://reports.ofsted.gov.uk/provider/23/139995

Searching for URN: 135851...
Found provider page: https://reports.ofsted.gov.uk/provider/22/135851

Searching for URN: 144588...
Found provider page: https://reports.ofsted.gov.uk/provider/23/144588

Searching for URN: 137785...
Found provider page: https://reports.ofsted.gov.uk/provider/27/137785

Searching for URN: 140429...
Found provider page: https://reports.ofsted.gov.uk/provider/23/140429

Searching for URN: 136094...
Found provider page: https://reports.ofsted.gov.uk/provider/16/136094

Searching for URN: 148654...
Found provider page: https://reports.ofsted.gov.uk/provider/25/148654

Searching for URN: 107802...
Found provider page: https://reports.ofsted.gov.uk/provider/25/107802

Searching for URN: 147067...
Found provider page: https://reports.ofsted.gov.uk/provider/23/147067

Searching for URN: 141002...
Found provider page: https://reports.ofsted.gov.uk/provider/23/141002

--- Final Ofsted Data ---
       URN OverallRating  Quality of education Behaviour and attitudes  \
0   139977   Outstanding                   NaN                     NaN
1   138251           NaN           Outstanding             Outstanding
2   137704           NaN           Outstanding             Outstanding
3   147100           NaN                   NaN                     NaN
4   135367           NaN  Requires Improvement                    Good
..     ...           ...                   ...                     ...
70  136094           NaN                   NaN                     NaN
71  148654           NaN                  Good                    Good
72  107802          Good                   NaN                     NaN
73  147067           NaN           Outstanding             Outstanding
74  141002           NaN                  Good                    Good

   Personal development Leadership and management  Sixth form provision  \
0                   NaN                       NaN                   NaN
1           Outstanding               Outstanding                   NaN
2           Outstanding               Outstanding           Outstanding
3                   NaN                       NaN                   NaN
4                  Good                      Good                  Good
..                  ...                       ...                   ...
70                  NaN                       NaN                   NaN
71                 Good                      Good  Requires Improvement
72                  NaN                       NaN                   NaN
73                 Good               Outstanding                   NaN
74                 Good                      Good                   NaN

   Early years provision
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                   Good
..                   ...
70                   NaN
71                   NaN
72                   NaN
73                   NaN
74                   NaN

[75 rows x 8 columns]

In [ ]:
df.to_csv("ofsted_school_scrape.csv", index=False)

In [ ]:
bradford_df.merge(
    df,
    left_on="URN",
    right_on="URN"
).to_csv("bradford_schools_w_ofsted.csv", index=False)

In [ ]:
bradford_ofsted_df = pd.read_csv("bradford_schools_w_ofsted.csv")

In [ ]:
bradford_ofsted_df

,Name,URN,Postcode,Lat,Lon,Website,Attainment 8,Progress 8,Pupil Count,OverallRating,Quality of education,Behaviour and attitudes,Personal development,Leadership and management,Sixth form provision,Early years provision
0,Hazelbeck Special School,139977,BD16 1EE,53.841401,-1.827540,https://www.hazelbeck.org/,NaN,NaN,11.0,Outstanding,NaN,NaN,NaN,NaN,NaN,NaN
1,Dixons Trinity Academy,138251,BD5 0BE,53.786414,-1.761281,https://www.dixonsta.com/,54.7,0.72,116.0,NaN,Outstanding,Outstanding,Outstanding,Outstanding,NaN,NaN
2,Otley Prince Henry's Grammar School Specialist...,137704,LS21 2BB,53.912570,-1.694590,https://www.princehenrys.co.uk/,53.4,0.34,278.0,NaN,Outstanding,Outstanding,Outstanding,Outstanding,Outstanding,NaN
3,Carlton Bolling,147100,BD3 0DU,53.802248,-1.738203,https://www.carltonbolling.co.uk/,43.0,0.27,323.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bradford Academy,135367,BD4 7QJ,53.776937,-1.732226,https://www.bradfordacademy.co.uk/,33.1,-0.94,230.0,NaN,Requires Improvement,Good,Good,Good,Good,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Trinity Academy Halifax,136094,HX2 9TZ,53.753928,-1.877149,https://halifax.trinitymat.org,43.5,0.00,318.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Green Meadows Academy,148654,LS20 8LS,53.874327,-1.721607,https://greenmeadows.org.uk/,7.3,-1.37,23.0,NaN,Good,Good,Good,Good,Requires Improvement,NaN
74,Fairfield School,107802,WF17 8AS,53.720996,-1.665745,https://www.fairfieldschool.uk/,NaN,NaN,10.0,Good,NaN,NaN,NaN,NaN,NaN,NaN
75,Bronte Girls' Secondary Academy,147067,BD4 7EB,53.785564,-1.745519,https://bga.iexel.org.uk/,51.2,0.21,127.0,NaN,Outstanding,Outstanding,Good,Outstanding,NaN,NaN
76,Dixons McMillan Academy,141002,BD5 0JD,53.786417,-1.765239,https://www.dixonsma.com/,47.8,-0.16,114.0,NaN,Good,Good,Good,Good,NaN,NaN

In [ ]:
df = pd.read_csv("ofsted_school_scrape.csv")

In [ ]:
df.loc[df.drop(columns=["URN"]).isnull().all(1)]["URN"]

C:\Users\halko\AppData\Local\Temp\ipykernel_10684\1709824954.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of all will be keyword-only.
  df.loc[df.drop(columns=["URN"]).isnull().all(1)]["URN"]

3     147100
7     108114
8     108117
11    107395
19    142590
23    150387
24    107455
26    136604
28    149162
32    148520
33    134427
36    138087
40    108083
46    150001
49    145173
52    107585
53    146204
55    136962
56    149519
60    134587
70    136094
Name: URN, dtype: int64

New ofsted rating system:
Exceptional
Strong standard
Expected standard
Needs attention
Urgent improvement

Old ofsted rating system:
    1 - outstanding
    2 - good
    3 - requires improvement
    4 - inadequate

In [ ]:
bradford_ofsted_df.loc[bradford_ofsted_df["URN"] == 146204, "OverallRating"] = "Good"

In [ ]:
bradford_ofsted_df.loc[bradford_ofsted_df["URN"] == 146204]

,Name,URN,Postcode,Lat,Lon,Website,Attainment 8,Progress 8,Pupil Count,OverallRating,Quality of education,Behaviour and attitudes,Personal development,Leadership and management,Sixth form provision,Early years provision
54,The Whitley AP Academy,146204,HX2 9SR,53.756066,-1.885915,https://twapa.co.uk/,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN
55,The Whitley AP Academy,146204,HX2 9SR,53.756957,-1.881179,https://twapa.co.uk/,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bradford_ofsted_df.to_csv("bradford_schools_w_ofsted.csv", index=False)

In [ ]:
indipendent_urns = [108114, ]

In [ ]:
# 147100 Carton Boiling: overall outstanding
# 108114 Woodhouse Grove School: independent
# 108117 Fulneck School: closed
# 107395 Titus Salt School: 
#       Post 16 provision: Strong Standard
#       Personal development and wellbeing: Expected Standard
#       Achievement: Needs attention
#       Attendance and behaviour: Needs attention
#       Curriculum and teaching: Needs attention
#       Inclusion: Needs attention
#       Leadership and governance: Needs attention
# 142590 Immanuel College: overall good
# 150387 The Calder Learning Trust: new academy, previously overall good
# 107455 Bradford Grammar School: independent
# 136604 Brighouse High School:
#       Attendance and behaviour: Expected Standard
#       Inclusion: Expected Standard
#       Personal development and wellbeing: Expected Standard
#       Post 16 provision: Expected Standard
#       Achievement: Needs attention
#       Curriculum and teaching: Needs attention
#       Leadership and governance: Needs attention
# 149162 Whitcliffe Mount, A Share Academy: overall good
# 148520 St Bede's and St Joseph's Catholic College, A Voluntary Academy: 
#       Post 16 provision: Strong standard
#       Attendance and behaviour: Expected Standard
#       Inclusion: Expected Standard
#       Personal development and wellbeing: Expected Standard
#       Achievement: Expected Standard
#       Curriculum and teaching: Expected Standard
#       Leadership and governance: Expected Standard
# 134427 TLG Bradford: Closed
# 138087 Belle Vue Girls' Academy:  
#       Personal development and wellbeing: Strong standard
#       Post 16 provision: Expected standard
#       Attendance and behaviour: Expected Standard
#       Inclusion: Expected Standard
#       Achievement: Expected Standard
#       Curriculum and teaching: Expected Standard
#       Leadership and governance: Expected Standard
# 108083 Benton Park School: new academy (previously Requires Improvement)
# 150001 Parkside School: new acaademy (previously Inadequate) 
# 145173 Appleton Academy:
#       Attendance and behaviour: Expected Standard
#       Inclusion: Expected Standard
#       Personal development and wellbeing: Expected Standard
#       Post 16 provision: Expected Standard
#       Achievement: Needs attention
#       Curriculum and teaching: Needs attention
#       Leadership and governance: Needs attention
# 107585 Hipperholme Grammar School: independent
# 146204 The Whitley AP Academy: overall good
# 136962 Feversham Girls' Secondary Academy: 
#       Attendance and behaviour: Strong Standard
#       Inclusion: Strong Standard
#       Personal development and wellbeing: Strong Standard
#       Achievement: Strong Standard
#       Curriculum and teaching: Strong Standard
#       Leadership and governance: Strong Standard
#       Post 16 provision: Expected Standard
# 149519 Oastlers School:
#       Attendance and behaviour: Exceptional
#       Inclusion: Exceptional
#       Personal development and wellbeing: Exceptional
#       Achievement: Exceptional
#       Curriculum and teaching: Exceptional
#       Leadership and governance: Exceptional
#       Post 16 provision: Exceptional
# 134587 The Fountain School: independent 
# 136094 Trinity Academy Halifax: overall outstanding
#       Quality of education: Outstanding
#       Behaviour and attitudes: Outstanding
#       Personal development: Outstanding
#       Leadership and management: Outstanding

In [ ]:
bradford_df.loc[bradford_df["URN"] == 136094]

,Name,URN,Postcode,Lat,Lon,Website,Attainment 8,Progress 8,Pupil Count
72,Trinity Academy Halifax,136094,HX2 9TZ,53.753928,-1.877149,https://halifax.trinitymat.org,43.5,0.0,318.0